"""empty message

Revision ID: 49f455bf4f08
Revises: 
Create Date: 2024-11-06 10:06:03.419387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49f455bf4f08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_name', sa.String(), nullable=True),
    sa.Column('restaurant_location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sandwiches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sandwich_name', sa.String(), nullable=True),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_sandwiches_restaurant_id_restaurants')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checkin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('sandwich_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sandwich_id'], ['sandwiches.id'], name=op.f('fk_checkin_sandwich_id_sandwiches')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_checkin_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checkin')
    op.drop_table('sandwiches')
    op.drop_table('users')
    op.drop_table('restaurants')
    # ### end Alembic commands ###
